spring:
  application:
    name: go-kirana-products
  jpa:
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080

app:
  pagination:
    max-size: 100